{% set name = "pydantic-collections" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydantic-collections-{{ version }}.tar.gz
  sha256: 4e8f7ef091e5bcc73e5008b3c1fa97222f5bf4219081bc346001b62a92ecd70b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=1.8.2

test:
  imports:
    - pydantic_collections
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/romis2012/pydantic-collections
  summary: Collections of pydantic models
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fgypas
